### ISSUE TITLE
Transfer all Pull requests

### ISSUE THREAD

**Issue by OmlineEditor** [adminerevo/adminerevo#3]
transfer all the edits that other users have made and let's start making a new program:
https://github.com/vrana/adminer/pulls
or you can write to other users so that they transfer their edits to you

**Comment by OmlineEditor** [comment]
are you still unable to contact the developer? he has his personal website, Twitter, and I've seen his mail somewhere. none of the channels are working for communication?

**Comment by LionelLaffineur** [comment]
I tried his email, I'm not on Twitter.

**Comment by OmlineEditor** [comment]
try to write to him again, perhaps the letter was not read due to the abundance of spam. having a direct connection with developers is very important and useful

**Comment by nitodico** [comment]
Not first time trying other developers has been trying to contact vrana... he's working at Google since 9 years ago, i guess he doesn't have enough spare time for OSS projects, his last pull req was 2 years ago, his latests commits were in december 2022... the best we can do i just keep the project alive and search collaborators, donors...

**Comment by OmlineEditor** [comment]
![Okay_meme](https://github.com/adminerevo/adminerevo/assets/13348933/054d78a0-7312-48d3-83a1-a7ef22697895)

**Comment by LionelLaffineur** [comment]
I'd really have preferred to continue with him, for the knowledge but also for the social aspect.  But since there is a real need to continue, I'm trying to rebuild a community and to continue the huge work.
It is really on the agenda to take over the pull requests, I'll start understanding and testing them one by one and to the adequate follow-up.
There are some for which I don't understand everything, I'll ask questions : feel free to help on commenting ;-)

**Comment by OmlineEditor** [comment]
if necessary, I will help, but I have little experience in PHP

**Comment by LionelLaffineur** [comment]
That should not be a problem.  Where we will need help is on testing on various DBMS we don't have in-house.

**Comment by LionelLaffineur** [comment]
Very good, I keep it in mind ;-)

**Comment by lukastribus** [comment]
![grafik](https://github.com/adminerevo/adminerevo/assets/15380567/1ae1c95d-94da-4ed5-bfdd-76f74b7d0c81)

Commenting on his youtube videos (this is from https://www.youtube.com/watch?v=OrOtiu_nfHE ) seems to be the only way to contact him at this point; however I doesn't sound like he has an immediate interests to handle organizational question regarding the original project.

I suggest to continue without him.

**Comment by LionelLaffineur** [comment]
Most of them have been integrated.  Others can always be reported in this project directly.
