### ISSUE TITLE
SELECT DISTINCT vs extra column id

### ISSUE THREAD

**Issue by LionelLaffineur** [adminerevo/adminerevo#40]
When the function DISTINCT is used in the SELECT page, whatever to which field the distinct should apply, the field id (table PK) is added making the result incorrect.
Why ?  How to fix ?

![image](https://github.com/adminerevo/adminerevo/assets/21120913/517ffa54-4c68-444e-9bc4-afd04e2f8c67)

**Comment by Lumeriol** [comment]
Problem is not with DISTINCT function, but with all functions, because their adds unselected primary keys to SELECT command. 

There is part of code start from [select.inc.php#276](https://github.com/adminerevo/adminerevo/blob/28232d91d3d3c6221fde12ce41d1b3042da9aea4/adminer/select.inc.php#L276), that checks grouping and add unselected primary keys to command.

In table with selected rows is used only columns from variables without "2" affix, so you will not see these keys.

**Comment by LionelLaffineur** [comment]
Dear @Lumeriol, dear anyone else,
I have implemented a "possible" fix here : https://github.com/adminerevo/adminerevo/commit/d347d59d3c3bb8bebf73e8620dc727a34069619b.
I don't find this fix elegant, nor I'm sure it doesn't break anything else !
Any comment / suggestion is welcome.
Regards,
L.

**Comment by LionelLaffineur** [comment]
@Lumeriol, I forgot to thank you for your contribution which was helpful !
