### ISSUE TITLE
Text on the left overflows into the main area

### ISSUE THREAD

**Issue by Kartoffelbauer** [adminerevo/adminerevo#58]
In some languages, such as In German, the text flows from the right side into the main area as shown in the following image:

![image](https://github.com/adminerevo/adminerevo/assets/64925487/e7425fd6-f63c-4e3e-acc3-13e5f6a62a26)

**Comment by LionelLaffineur** [comment]
Hi @Kartoffelbauer, thanks for reporting this.

I will add on top what's going on with the tables list when table names are longer than the space allowed:
![Screenshot from 2023-09-21 07-33-41](https://github.com/adminerevo/adminerevo/assets/21120913/60246616-4a3e-4767-9af5-d666e1f3a8a0)
and on mouse over:
![Screenshot from 2023-09-21 07-34-13](https://github.com/adminerevo/adminerevo/assets/21120913/4d24dbae-eb23-4bf7-bd77-456823cf30f8)
I don't know if it is ideal, if it is the best practice, it is just a report of the current situation.

What I am sure of, is that I am open to any suggestion on how to handle that.  I've faced that problem in many web applications and various solutions (good and bad) were used to fix it, mainly depending on the situation.

@SanderVanKeer, @Roy-Orbison, anyone else : suggestions ?

What I would think first would be to break line.  For table names, it would make it somehow more difficult to read but would remain better than not seeing the full name without hovering.
Where I have a problem with this solution, is with the | separator that I have introduced for readability.  I wouldn't look nice to end line or start new line with a separator.
If this would be a valuable solution, any suggestion on how to handle the separators is welcome.

Thanks in advance,
L.

**Comment by Roy-Orbison** [comment]
The table names overflowing on hover is deliberate (and probably the best solution), otherwise the table list gets too wide, or must be scrolled horizontally to see long tables names. They also have a background colour applied to ensure they're readable.

The other links overflowing like that is just a visual bug, they should wrap. It was done [over a decade ago](https://github.com/adminerevo/adminerevo/commit/340a1c2c2ff8077f565b915a7b4c055f7c7cac16#diff-2585ed2e1e2b7cfc97e9c8db10553f6ed1997ddd67ae21b269bc8a7106657f10). Maybe the intention was to stop individual links from breaking across lines, as it's better to wrap before the entire link rather than within it. This could be done by setting `display: inline-block` and removing `white-space: nowrap` on the link. Flexbox is another alternative.

**Comment by LionelLaffineur** [comment]
Issue is fixed through this commit: https://github.com/adminerevo/adminerevo/commit/fb3d58ce5d24705b002d03bcc3cd1160e7b4d460.

Thanks for reporting.
